### ISSUE TITLE
Слетает установленное активное состояние у пользовательского запроса 

### ISSUE THREAD

**Issue by TonyLevsha** [artemyakovlev94/simple#10]
![image](https://github.com/artemyakovlev94/simple/assets/164510354/5eaea51d-c197-4511-8341-ee375166ebd0)
При установке использования пользовательского запроса слетает данная настройка при выходе из окна настройки подсистем. На процесс не влияет получения данных с МП через /user_query не влияет.

**Comment by artemyakovlev94** [comment]
Исправлено в версии 1.0.0.7
