### ISSUE TITLE
1.0.0.7 код 403 для "Пользователь ТСД" при использовании запросов группового пересчета

### ISSUE THREAD

**Issue by TonyLevsha** [artemyakovlev94/simple#11]
![image](https://github.com/artemyakovlev94/simple/assets/164510354/b9431d8a-4137-411e-ad24-49a09cc5604a)
Версия расширения 1С 1.0.0.7
Права доступа пользователя: Simple: ТСД, Базовые права БСП
ошибка 403 при следующих запросах:
document_lines/overwrite
document_lines/finish

**Comment by artemyakovlev94** [comment]
Исправлено в версии 1.0.0.8
