### ISSUE TITLE
1.0.0.8 sandbox Ошибка при запросе /LA/balances_prices если не передана характеристика

### ISSUE THREAD

**Issue by TonyLevsha** [artemyakovlev94/simple#12]
![image](https://github.com/artemyakovlev94/simple/assets/164510354/0c0b04b9-9e2b-4aa2-af14-ae4cd7211822)
![image](https://github.com/artemyakovlev94/simple/assets/164510354/ecd4066f-68c1-4641-927c-35e6be13c3ab)
500 Ошибка "передано значение недопустимого типа" при запросе остатков и цен, если не передана характеристика. 
Проверено на 1.0.0.6 - если в запросе был передан id_good без id_property, в ответе получаем "StatusCode": 200.

**Comment by artemyakovlev94** [comment]
Исправлено в 1.0.0.8
