### ISSUE TITLE
1.0.0.8 Simple_ut_sandbox Не активные поля выбора в "Настройки документов"

### ISSUE THREAD

**Issue by TonyLevsha** [artemyakovlev94/simple#18]
После обновления расширения 19.04.2024 в настройках документов обмена не активны поля выбора из списка во вкладках "Сопоставление реквизитов" (Склад, Контрагент) и "После загрузки" - "Установка реквизитов" (Реквизит документа)
![image](https://github.com/artemyakovlev94/simple/assets/164510354/a3d61926-8543-4d60-a0a3-0cda3561c653)

**Comment by artemyakovlev94** [comment]
Исправлено в 1.0.0.8
