### ISSUE TITLE
1.0.2.1 Ошибка при авторизации мобильного клиента

### ISSUE THREAD

**Issue by TonyLevsha** [artemyakovlev94/simple#21]
После обновления до версии 1.0.2.1 Ошибка при попытке авторизовать мобильного клиента 
![image](https://github.com/artemyakovlev94/simple/assets/164510354/b573538c-e937-423f-b798-82efd1d0b29c)

Ошибка при вызове метода контекста (Записать)
{Simple ОбщийМодуль.SUI_МобильныеУстройстваСервер.Модуль(357)}:МобильноеУстройство = МобильноеУстройство(МобильноеУстройство);
{Simple ОбщийМодуль.SUI_МобильныеУстройстваСервер.Модуль(115)}:ВыполнитьПолнуюВыгрузку(Источник.Ссылка);
{Simple ОбщийМодуль.SUI_МобильныеУстройстваСервер.Модуль(176)}:МобильноеУстройствоОбъект.Записать();
{Simple ОбщийМодуль.SUI_МобильныеУстройстваСервер.Модуль(509)}:МобильныйКлиентОбъект.Записать();
{Simple ОбщийМодуль.SUI_МобильныеУстройстваСервер.Модуль(249)}:МобильныйКлиент = СоздатьМобильногоКлиента(ДанныеЗапросаАвторизации.ИдентификаторУстройства,
{Simple ОбщийМодуль.SUI_МобильныеУстройстваВызовСервера.Модуль(17)}:Возврат SUI_МобильныеУстройстваСервер.ПринятьЗапросАвторизацииУстройства(ИдентификаторУстройства);
{Simple ОбщийМодуль.SUI_МобильныеУстройстваКлиент.Модуль(90)}:МобильныйКлиент = SUI_МобильныеУстройстваВызовСервера.ПринятьЗапросАвторизацииУстройства(ИдентификаторУстройства);
{mngcore/MessageBox.clf(4)}:Close(-100);

по причине:
Ошибка при выполнении обработчика - 'ПриЗаписи'
по причине:
Ошибка при вызове метода контекста (Записать)
по причине:
Ошибка при выполнении обработчика - 'ПриЗаписи'
по причине:
Поле объекта недоступно для записи (Ссылка)

**Comment by artemyakovlev94** [comment]
Исправлено 1.0.2.1
