### ISSUE TITLE
Обращение к РС SUI_НастройкиДокументовМобильныхКлиентов в Настройке документов

### ISSUE THREAD

**Issue by PolinaZHe** [artemyakovlev94/simple#24]
В справочнике Настройка документов на вкладке "Настройка документов мобильных **клиентов**" (поменять на "...устройств") при нажатии на "Заполнить" возвращается ошибка (см скрин). Мобильное устройство не добавляется в список.
![Настройка документов](https://github.com/artemyakovlev94/simple/assets/173356045/d14968db-a6af-4977-b998-6de5f4856174)

**Comment by artemyakovlev94** [comment]
Исправлено в 1.0.3.11
