### ISSUE TITLE
Добавить права в "Simple: Базовые права"

### ISSUE THREAD

**Issue by TonyLevsha** [artemyakovlev94/simple#26]
Офф-лайн обмен. Ошибка доступа для пользователя с базовыми правами Simple по кнопке "Загрузить данные" (на скрине отметила "+" кнопки, по которым у пользователя нет ошибок)
![image](https://github.com/artemyakovlev94/simple/assets/164510354/79f8abcc-8939-443a-a049-c1914a8a2a87)

Он-лайн обмен. Ошибка доступа для пользователя с базовыми правами Simple при записи загруженных данных в документ
![image](https://github.com/artemyakovlev94/simple/assets/164510354/1960ba6f-b421-489b-aa78-6053f5224b34)

Тестировалось:
1) http://192.168.0.39/ut_test (версия расширения 1.0.3.12)
2) Моя локальная база с версией расширения 1.0.4.2
Мой юзер
![image](https://github.com/artemyakovlev94/simple/assets/164510354/76f56376-e0ad-4dcb-8685-69d61e0d7d2a)

**Comment by Ilya-cod** [comment]
Исправлено в версии 1.0.3.13

**Comment by TonyLevsha** [comment]
1.0.1.3.13 Базовые права Simple, ошибка при загрузке данных по потоковому сканированию
![image](https://github.com/artemyakovlev94/simple/assets/164510354/345147bc-daaf-496b-83db-cac082b55a62)


На этом всё. Проверены оба режима обмена: он-лайн и офф-лайн.
![image](https://github.com/artemyakovlev94/simple/assets/164510354/14f16461-cd66-4100-a0b3-bdeaa83b894b)

**Comment by TonyLevsha** [comment]
Офф-лайн обмен, логирование запросов. 
![image](https://github.com/artemyakovlev94/simple/assets/164510354/f0e17dab-5648-4802-ac57-6416a7bcacb9)
